highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: 'https://kdshim.github.io'
baseurl: '/'
author: Kidong Shim

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: ""
title: Kidong Shim
name: Kidong Shim
email: shimkidong@gmail.com
email_full: mailto:shimkidong@gmail.com
website: github.io
website_full: /
github: https://github.com/kdshim
twitter: twitter
tel: +44 0000 000000
tel_full: tel:+440000000000
address:
  street:
  postcode:
  city:
  country:
# needed for travis-ci build
exclude: [vendor]
