highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: 'https://K-I-M-J-I-N.github.io'
baseurl: '/'
author: Jin Kim

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: ""
title: Jin Kim
name: Jin Kim
email: jinmerong@gmail.com
email_full: mailto:jinmerong@gmail.com
website: github.io
website_full: /
github: https://github.com/K-I-M-J-I-N
twitter: twitter
tel: +44 0000 000000
tel_full: tel:+440000000000
address:
  street:
  postcode:
  city:
  country:
# needed for travis-ci build
exclude: [vendor]
